"tool.name"       = "bold #f9e2af"
"tool.arg.key"    = "#89dceb"
"tool.arg.val"    = "#585b70"
"tool.result"     = "#585b70"
"agent.indicator" = "#585b70"
"agent.text"      = "#cdd6f4"
"error"           = "bold #f38ba8"
"info"            = "#585b70"
"heading"         = "bold #89b4fa"
"cmd"             = "bold #a6e3a1"
_border           = "#89b4fa"
_model            = "#cba6f7"
_prompt           = "#89b4fa"
_code             = "monokai"
