"tool.name"       = "bold #fabd2f"
"tool.arg.key"    = "#83a598"
"tool.arg.val"    = "#665c54"
"tool.result"     = "#665c54"
"agent.indicator" = "#665c54"
"agent.text"      = "#ebdbb2"
"error"           = "bold #fb4934"
"info"            = "#7c6f64"
"heading"         = "bold #83a598"
"cmd"             = "bold #b8bb26"
_border           = "#83a598"
_model            = "#fabd2f"
_prompt           = "#fe8019"
_code             = "gruvbox-dark"
