"tool.name"       = "bold #ebcb8b"
"tool.arg.key"    = "#88c0d0"
"tool.arg.val"    = "#4c566a"
"tool.result"     = "#4c566a"
"agent.indicator" = "#4c566a"
"agent.text"      = "#d8dee9"
"error"           = "bold #bf616a"
"info"            = "#4c566a"
"heading"         = "bold #81a1c1"
"cmd"             = "bold #a3be8c"
_border           = "#88c0d0"
_model            = "#81a1c1"
_prompt           = "#88c0d0"
_code             = "nord-darker"
